# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SSSWebSocketClient" do

pod 'AZSocketIO', '~> 0.0.5'

end

target "SSSWebSocketClientTests" do

end

